require "config"
require "modules.reload"
require "modules.auto_input_method"
require "modules.clipboard"
-- require "modules.window"
require "modules.hotkey"
require "modules.launcher"
require "modules.network"
require "modules.winwin"

